### ISSUE TITLE
demo not working

### ISSUE THREAD

**Issue by ngugijames** [dptole/laravel-survey#1]
![screen shot 2018-06-04 at 10 23 46](https://user-images.githubusercontent.com/6430405/40903829-6e2635c6-67e1-11e8-99b8-daba120caeb5.png)

**Comment by dptole** [comment]
@ngugijames thanks for your interest!

I was asked to host this website for a client while it is in development mode. The demo will be back, hopefully, at the end of this month.

**Comment by ngugijames** [comment]
thanks!
