### ISSUE TITLE
Error npm run dev

### ISSUE THREAD

**Issue by geshtng** [dptole/laravel-survey#2]
I have some errors when I run `npm run dev`
This is the screenshot:
![image](https://user-images.githubusercontent.com/29280690/53571838-6bbd0f00-3b9c-11e9-8034-32f451f0df65.png)
.
How can I fix that?

**Comment by dptole** [comment]
@geshtng you should Install the dependencies, by running the command below, before you run `npm run dev`

```
npm i
```

> `npm i` is the same as `npm install`
