### ISSUE TITLE
questions.js not found

### ISSUE THREAD

**Issue by Emmanuel-ob** [dptole/laravel-survey#5]
The question.js was not part of the files that were downloaded, as a result the application does not allow me to enter answer options when i run the application.
Kindly assist.

**Comment by dptole** [comment]
@Emmanuel-ob this file should be automatically generated when you run

```shellscript
$ npm run dev
OR
$ npm run production
```

These commands will generate the JS files as described by [webpack.mix.js](https://github.com/dptole/laravel-survey/blob/master/webpack.mix.js). If it doesn't work post the error message please

**Comment by Emmanuel-ob** [comment]
Thanks.
It seem I mistakenly skipped this step.
